### ISSUE TITLE
Removes existing html classes (on Magento CMS)

### ISSUE THREAD

**Issue by jcanepa** [acolangelo/jPanelMenu#100]
I implemented jPanelMenu on a Magento CMS site, and noticed the existing <html> classes were removed/replaced. Not sure why this happened, since the jQ function used, addClass(); should only add the class specified, not remove any others. Also when removeClass(); is used, it explicitly refers to the same one that was added.

Please advise, thanks

**Comment by acolangelo** [comment]
Which element were the classes being removed from? This hasn’t been seen before, so I’m wondering if there’s a link somewhere I could take a look at?
