### ISSUE TITLE
The menu always gets the width 250px;

### ISSUE THREAD

**Issue by ankit-link** [acolangelo/jPanelMenu#106]
What if I want it to be more?

**Comment by acolangelo** [comment]
Use the [`openPosition`](http://jpanelmenu.com/#options-openPosition) option to customize the width of the menu.

**Comment by ankit-link** [comment]
Thanks Anthony Colangelo

On Thu, May 28, 2015 at 7:34 PM, Anthony Colangelo <notifications@github.com
