### ISSUE TITLE
Inline 'position: relative' attribute on .jPanelMenu-panel element interferes with Bootstrap modal

### ISSUE THREAD

**Issue by ryanpsims** [acolangelo/jPanelMenu#13]
Hi,

It seems like the initial setup of a panel instance interferes with modal z-indexing in Bootstrap. 

Bootstrap sets a z-index for the modal, and the semi-opaque div that appears below it at 1050, and 1040 respectively. When jPanel runs, the modal gets included inside of the .jPanelMenu-panel element. However, bootstrap dynamically inserts the semi-opaque 'modal-backdrop' div dynamically at the end of the body. Because of the position relative being applied to the parent of the modal, the modal appears beneath the backdrop.

Specifically if you change the inline style of 'position: relative' applied to the .jPanelMenu-panel to 'position:static', things work as expected.

Got a work around? In an upcoming release could you change the initial setting for position to static?

**Comment by imteekay** [comment]
I'm using the most updated version of JPanelMenu, but my bootstrap modal is not working.
It has the "panelPosition: 'static'" updated.

I also tried something like that:
excludedPanelContent: 'style, script, .modal'
..but no success..

The modal opens proprerly but the modal-backdrop is in front of the modal.

Any thoughts?
