### ISSUE TITLE
Where is the SS-list icon?

### ISSUE THREAD

**Issue by Calimero876** [acolangelo/jPanelMenu#42]
I sitting here for some days- The Menu is running but where is the ss-list icon? How can i insert it, because everything i did didn't work.

Only this  icon is shown. not the wonderful apple touch icon.

SO there is a big lack of documentation. What can i do?

**Comment by Quasaur** [comment]
I certainly sympathize with the Author's position, but there's a lot of us noobs out there; perhaps mentioning these type of dependencies (like the SSStandard font and TypeKit) might help and how to replace them with our own resources...?
