### ISSUE TITLE
wrapAll Causing Document.Ready() To Run Twice

### ISSUE THREAD

**Issue by pawl** [acolangelo/jPanelMenu#63]
This line in jquery.jpanelmenu.js was causing my document.ready() at the bottom of my script to run twice:

```
$('body > *').not(jP.menu + ', ' + jP.options.excludedPanelContent).wrapAll('<div class="' + 'jPanelMenu-panel' + '"/>');
```

I needed to comment it out and wrap everything in your body tag manually with:

```
<div class="jPanelMenu-panel" style="position: relative; left: 0px;">
</div>
```

The end result looked like:

```
<body>
<div class="jPanelMenu-panel" style="position: relative; left: 0px;">
all your code....
</div>
</body>
```

This page helped me figure it out: http://doctype.com/trying-jquery-wrapall-seems-wrap-content-twice

**Comment by drywall** [comment]
I'm having this problem too, despite the excludedPanelContent being left as the default

**Comment by drywall** [comment]
It looks like the use of excludedPanelContent is only set up to catch elements that are direct children of the panel element (usually 'body').

Seems like this line:

```
    $(jP.options.panel + ' > *').not(jP.menu + ', ' + jP.options.excludedPanelContent).wrapAll('<div class="' + jP.panel.replace('.','') + '"/>');
```

Needs to be rewritten to do a deep traversal of `$(jP.options.panel + ' > *')` and remove elements found in excludedPanelContent. Or something like that?
