### ISSUE TITLE
sub menus?

### ISSUE THREAD

**Issue by flashtopia** [acolangelo/jPanelMenu#98]
are they supported?  slide out like ipod

**Comment by acolangelo** [comment]
This plugin _only_ handles the creation and trigger of the menu element. Anything that happens within the menu (or anywhere else on the page) is entirely up to you and your site’s code.

Hooks are provided to be able to run code at appropriate times. Check out the [options section](http://jpanelmenu.com/#options) of the documentation to see what hooks are available.

So, yes! They are supported, but you’ll have to create that functionality in your site’s code. Hope that helps!
