### ISSUE TITLE
How to do open the left menu, right folding content disable scroll?

### ISSUE THREAD

**Issue by note4** [acolangelo/jPanelMenu#99]
How to do open the left menu, right folding content disable scroll?

我也是醉了，打开左侧菜单时，右侧的内容居然还可以滑动，还会连左侧菜单也拖上去一些看到灰色背景。

**Comment by acolangelo** [comment]
If I’m understanding the question correctly, you want to disable scroll on the content when the menu is open? You’d probably want to set the `body` to `overflow: hidden` to disable scrolling in that way. Hope that helps!
